# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-29 11:48
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='weatherforecast',
            name='today_date',
            field=models.DateField(default=datetime.datetime(2016, 11, 29, 11, 48, 23, 302711, tzinfo=utc)),
            preserve_default=False,
        ),
    ]
